name: Bot 2 Ultra Sniper (Auto-Train & Signal)

on:
  schedule:
    - cron: '*/5 * * * *' # Bot jalan otomatis unggal 5 menit
  workflow_dispatch: # Bisa dijalankeun manual

jobs:
  run-bot-mastermind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Auto Train AI Bot 2
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python train_ai_bot2.py

      - name: Execute Bot Signal Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python bot_signal_bot2.py
